let prompt=require('prompt-sync')()
let a=prompt("enter the marks : ")
if(a>=90)
    console.log("Grade A")
else if((a>=80)&&(a<90))
    console.log("Grade B")
else if((a>=70)&&(a<80))
    console.log("Grade C")
else if((a>=60)&&(a<70))
    console.log("Grade D")
else
    console.log("Failed ")